implementations = {...
    @(A) symordering.minimum_degree_impl.minimum_degree(A), ...
    @(A) symordering.minimum_degree_impl.minimum_degree_mass_elimination(A), ...
};

symordering.tests.test_equivalent_implementations_randomly(implementations);
disp('Minimum degree implementations seem to work correctly.');
