implementations = {...
    @(A) symordering.minimum_local_fill_impl.minimum_local_fill(A), ...
    @(A) symordering.minimum_local_fill_impl.minimum_local_fill_fewer_updates(A), ...
};

symordering.tests.test_equivalent_implementations_randomly(implementations);
disp('Minimum local fill implementations seem to work correctly.');
